version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: all
  # disable:
  #   - wsl

  exclusions:
    generated: strict
    warn-unused: false
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: strict
